// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIAE_LA.Infrastructure.Persistence;

#nullable disable

namespace SIAE_LA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("p_k_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.HasKey("UserId", "RoleId")
                        .HasName("p_k_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("p_k_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.HasKey("Id")
                        .HasName("p_k_alumno");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_alumno_persona_id");

                    b.ToTable("alumno", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.AlumnoApoderado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alumno_apoderado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<int>("ApoderadoId")
                        .HasColumnType("integer")
                        .HasColumnName("apoderado_id");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<bool>("EsResponsableLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_responsable_legal");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.HasKey("Id")
                        .HasName("p_k_alumno_apoderado");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("i_x_alumno_apoderado_alumno_id");

                    b.HasIndex("ApoderadoId")
                        .HasDatabaseName("i_x_alumno_apoderado_apoderado_id");

                    b.HasIndex("AlumnoId", "FechaFin")
                        .HasDatabaseName("i_x__a_l_u_m_n_o__a_p_o_d_e_r_a_d_o__a_l_u_m_n_o__f_e_c_h_a_f_i_n");

                    b.ToTable("alumno_apoderado", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.AnioLectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("anio_lectivo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.HasKey("Id")
                        .HasName("p_k_anio_lectivo");

                    b.ToTable("anio_lectivo", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Apoderado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("apoderado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("TipoParentesco")
                        .HasColumnType("text")
                        .HasColumnName("tipo_parentesco");

                    b.HasKey("Id")
                        .HasName("p_k_apoderado");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_apoderado_persona_id");

                    b.ToTable("apoderado", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("aprobado_por");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("es_email_confirmado");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_aprobado");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("es_telefono_confirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_usuarios_persona_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<int>("CurriculaId")
                        .HasColumnType("integer")
                        .HasColumnName("curricula_id");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota");

                    b.Property<int?>("PeriodoId")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_id");

                    b.HasKey("Id")
                        .HasName("p_k_calificacion");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("i_x_calificacion_alumno_id");

                    b.HasIndex("PeriodoId")
                        .HasDatabaseName("i_x_calificacion_periodo_id");

                    b.HasIndex("CurriculaId", "AlumnoId")
                        .IsUnique()
                        .HasDatabaseName("ux_calificacion_curricula_alumno");

                    b.ToTable("calificacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_calificacion_nota", "nota >= 0 AND nota <= 100");
                        });
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("curricula_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DocenteNivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("docente_nivel_detalle_curso_id");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int?>("NivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    b.HasKey("Id")
                        .HasName("p_k_curricula");

                    b.HasIndex("DocenteNivelDetalleCursoId")
                        .HasDatabaseName("i_x_curricula_docente_nivel_detalle_curso_id");

                    b.HasIndex("NivelDetalleCursoId")
                        .HasDatabaseName("i_x_curricula_nivel_detalle_curso_id");

                    b.ToTable("curricula", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.HasKey("Id")
                        .HasName("p_k_curso");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("ix_curso_codigo");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("docente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GradoEstudio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grado_estudio");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.HasKey("Id")
                        .HasName("p_k_docente");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("i_x_docente_persona_id");

                    b.ToTable("docente", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("docente_nivel_detalle_curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer")
                        .HasColumnName("docente_id");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("NivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    b.HasKey("Id")
                        .HasName("p_k_docente_nivel_detalle_curso");

                    b.HasIndex("DocenteId")
                        .HasDatabaseName("i_x_docente_nivel_detalle_curso_docente_id");

                    b.HasIndex("NivelDetalleCursoId", "DocenteId")
                        .IsUnique()
                        .HasDatabaseName("i_x_docente_nivel_detalle_curso_nivel_detalle_curso_id_docente_~");

                    b.ToTable("docente_nivel_detalle_curso", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.GradoSeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grado_seccion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("DescripcionGrado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion_grado");

                    b.Property<string>("DescripcionSeccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion_seccion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.HasKey("Id")
                        .HasName("p_k_grado_seccion");

                    b.ToTable("grado_seccion", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("horario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dia_semana");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("NivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    b.HasKey("Id")
                        .HasName("p_k_horario");

                    b.HasIndex("NivelDetalleCursoId")
                        .HasDatabaseName("i_x_horario_nivel_detalle_curso_id");

                    b.ToTable("horario", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matricula_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<int?>("AnioLectivoId")
                        .HasColumnType("integer")
                        .HasColumnName("anio_lectivo_id");

                    b.Property<int?>("ApoderadoId")
                        .HasColumnType("integer")
                        .HasColumnName("apoderado_id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<bool?>("EsRepitente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_repitente");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InstitucionProcedencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("institucion_procedencia");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("NivelDetalleId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_id");

                    b.Property<string>("Situacion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("situacion");

                    b.Property<string>("ValorCodigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("valor_codigo");

                    b.HasKey("Id")
                        .HasName("p_k_matricula");

                    b.HasIndex("AnioLectivoId")
                        .HasDatabaseName("i_x_matricula_anio_lectivo_id");

                    b.HasIndex("ApoderadoId")
                        .HasDatabaseName("i_x_matricula_apoderado_id");

                    b.HasIndex("NivelDetalleId")
                        .HasDatabaseName("i_x_matricula_nivel_detalle_id");

                    b.HasIndex("AlumnoId", "NivelDetalleId", "AnioLectivoId")
                        .IsUnique()
                        .HasDatabaseName("i_x_matricula_alumno_id_nivel_detalle_id_anio_lectivo_id");

                    b.ToTable("matricula", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("DescripcionNivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion_nivel");

                    b.Property<string>("DescripcionTurno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion_turno");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Horario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("horario");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.HasKey("Id")
                        .HasName("p_k_nivel");

                    b.ToTable("nivel", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GradoSeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("grado_seccion_id");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    b.Property<int?>("TotalVacantes")
                        .HasColumnType("integer")
                        .HasColumnName("total_vacantes");

                    b.Property<int?>("VacantesOcupadas")
                        .HasColumnType("integer")
                        .HasColumnName("vacantes_ocupadas");

                    b.HasKey("Id")
                        .HasName("p_k_nivel_detalle");

                    b.HasIndex("GradoSeccionId")
                        .HasDatabaseName("i_x_nivel_detalle_grado_seccion_id");

                    b.HasIndex("NivelId", "GradoSeccionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_nivel_detalle_nivel_id_grado_seccion_id");

                    b.ToTable("nivel_detalle", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalleCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("NivelDetalleId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_id");

                    b.HasKey("Id")
                        .HasName("p_k_nivel_detalle_curso");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("i_x_nivel_detalle_curso_curso_id");

                    b.HasIndex("NivelDetalleId", "CursoId")
                        .IsUnique()
                        .HasDatabaseName("i_x_nivel_detalle_curso_nivel_detalle_id_curso_id");

                    b.ToTable("nivel_detalle_curso", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("periodo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int?>("AnioLectivoId")
                        .HasColumnType("integer")
                        .HasColumnName("anio_lectivo_id");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("p_k_periodo");

                    b.HasIndex("AnioLectivoId", "Orden")
                        .HasDatabaseName("ix_periodo_anio_orden");

                    b.ToTable("periodo", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Direccion")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("direccion");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroTelefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_telefono");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sexo");

                    b.Property<string>("ValorCodigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("valor_codigo");

                    b.HasKey("Id")
                        .HasName("p_k_persona");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique()
                        .HasDatabaseName("i_x_persona_documento_identidad");

                    b.ToTable("persona", null, t =>
                        {
                            t.HasCheckConstraint("CK_PERSONA_DOCID_FORMAT", "(\r\n                        documento_identidad ~ '^\\d{3}-\\d{6}-\\d{3,4}[A-Z]?$'\r\n                        OR documento_identidad ~ '^TUTOR-\\d{3}-\\d{6}-\\d{3,4}[A-Z]?$'\r\n                      )");

                            t.HasCheckConstraint("CK_PERSONA_SEXO", "sexo IN ('M','F','O')");

                            t.HasCheckConstraint("CK_PERSONA_TEL_NI", "(\r\n                        numero_telefono IS NULL\r\n                        OR numero_telefono ~ '^\\+505\\d{8}$'\r\n                        OR numero_telefono ~ '^\\d{8}$'\r\n                      )");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asp_net_user_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Alumno", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne("Alumno")
                        .HasForeignKey("SIAE_LA.Domain.Entities.Alumno", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alumno_persona_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.AlumnoApoderado", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Apoderados")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alumno_apoderado_alumno_alumno_id");

                    b.HasOne("SIAE_LA.Domain.Entities.Apoderado", "Apoderado")
                        .WithMany()
                        .HasForeignKey("ApoderadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_alumno_apoderado_apoderado_apoderado_id");

                    b.Navigation("Alumno");

                    b.Navigation("Apoderado");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Apoderado", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne("Apoderado")
                        .HasForeignKey("SIAE_LA.Domain.Entities.Apoderado", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_apoderado_persona_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("SIAE_LA.Domain.Entities.ApplicationUser", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_usuarios_persona_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Calificaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_calificacion_alumno_alumno_id");

                    b.HasOne("SIAE_LA.Domain.Entities.Curricula", "Curricula")
                        .WithMany("Calificaciones")
                        .HasForeignKey("CurriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_calificacion_curricula_curricula_id");

                    b.HasOne("SIAE_LA.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_calificacion_periodo_periodo_id");

                    b.Navigation("Alumno");

                    b.Navigation("Curricula");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curricula", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", "DocenteNivelDetalleCurso")
                        .WithMany("Curriculas")
                        .HasForeignKey("DocenteNivelDetalleCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_curricula_docente_nivel_detalle_curso_docente_nivel_detalle~");

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalleCurso", null)
                        .WithMany("Curriculas")
                        .HasForeignKey("NivelDetalleCursoId")
                        .HasConstraintName("f_k_curricula_nivel_detalle_curso_nivel_detalle_curso_id");

                    b.Navigation("DocenteNivelDetalleCurso");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Docente", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne("Docente")
                        .HasForeignKey("SIAE_LA.Domain.Entities.Docente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_docente_persona_persona_id");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Docente", "Docente")
                        .WithMany("Asignaciones")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_docente_nivel_detalle_curso_docente_docente_id");

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalleCurso", "NivelDetalleCurso")
                        .WithMany("Docentes")
                        .HasForeignKey("NivelDetalleCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_docente_nivel_detalle_curso_nivel_detalle_curso_nivel_detal~");

                    b.Navigation("Docente");

                    b.Navigation("NivelDetalleCurso");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Horario", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalleCurso", "NivelDetalleCurso")
                        .WithMany("Horarios")
                        .HasForeignKey("NivelDetalleCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_horario_nivel_detalle_curso_nivel_detalle_curso_id");

                    b.Navigation("NivelDetalleCurso");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_matricula_alumno_alumno_id");

                    b.HasOne("SIAE_LA.Domain.Entities.AnioLectivo", "AnioLectivo")
                        .WithMany("Matriculas")
                        .HasForeignKey("AnioLectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_matricula_anio_lectivo_anio_lectivo_id");

                    b.HasOne("SIAE_LA.Domain.Entities.Apoderado", "Apoderado")
                        .WithMany("Matriculas")
                        .HasForeignKey("ApoderadoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_matricula_apoderado_apoderado_id");

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalle", "NivelDetalle")
                        .WithMany("Matriculas")
                        .HasForeignKey("NivelDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_matricula_nivel_detalle_nivel_detalle_id");

                    b.Navigation("Alumno");

                    b.Navigation("AnioLectivo");

                    b.Navigation("Apoderado");

                    b.Navigation("NivelDetalle");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalle", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.GradoSeccion", "GradoSeccion")
                        .WithMany("NivelDetalles")
                        .HasForeignKey("GradoSeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_nivel_detalle_grado_seccion_grado_seccion_id");

                    b.HasOne("SIAE_LA.Domain.Entities.Nivel", "Nivel")
                        .WithMany("Detalles")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_nivel_detalle_nivel_nivel_id");

                    b.Navigation("GradoSeccion");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalleCurso", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Curso", "Curso")
                        .WithMany("Niveles")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_nivel_detalle_curso_curso_curso_id");

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalle", "NivelDetalle")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_nivel_detalle_curso_nivel_detalle_nivel_detalle_id");

                    b.Navigation("Curso");

                    b.Navigation("NivelDetalle");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Periodo", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.AnioLectivo", "AnioLectivo")
                        .WithMany("Periodos")
                        .HasForeignKey("AnioLectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_periodo_anio_lectivo_anio_lectivo_id");

                    b.Navigation("AnioLectivo");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("Apoderados");

                    b.Navigation("Calificaciones");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.AnioLectivo", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Apoderado", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curricula", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", b =>
                {
                    b.Navigation("Curriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.GradoSeccion", b =>
                {
                    b.Navigation("NivelDetalles");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Nivel", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalle", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalleCurso", b =>
                {
                    b.Navigation("Curriculas");

                    b.Navigation("Docentes");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Alumno");

                    b.Navigation("Apoderado");

                    b.Navigation("Docente");
                });
#pragma warning restore 612, 618
        }
    }
}
