// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIAE_LA.Infrastructure.Persistence;

#nullable disable

namespace SIAE_LA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("alumno", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.AlumnoApoderado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("alumno_apoderado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("ApoderadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsResponsableLegal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_responsable_legal");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ApoderadoId");

                    b.HasIndex("AlumnoId", "FechaFin")
                        .HasDatabaseName("IX_ALUMNO_APODERADO_ALUMNO_FECHAFIN");

                    b.ToTable("alumno_apoderado", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Apoderado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("apoderado_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text")
                        .HasColumnName("estado_civil");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("TipoParentesco")
                        .HasColumnType("text")
                        .HasColumnName("tipo_parentesco");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("apoderado", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("aprobado_por");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("es_email_confirmado");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_aprobado");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("es_telefono_confirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<int>("CurriculaId")
                        .HasColumnType("integer")
                        .HasColumnName("curricula_id");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CurriculaId", "AlumnoId")
                        .IsUnique()
                        .HasDatabaseName("ux_calificacion_curricula_alumno");

                    b.ToTable("calificacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_calificacion_nota", "nota >= 0 AND nota <= 100");
                        });
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("curricula_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DocenteNivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("docente_nivel_detalle_curso_id");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int?>("NivelDetalleCursoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocenteNivelDetalleCursoId");

                    b.HasIndex("NivelDetalleCursoId");

                    b.ToTable("curricula", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("ix_curso_codigo");

                    b.ToTable("curso", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("docente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("GradoEstudio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grado_estudio");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("docente", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("docente_nivel_detalle_curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer")
                        .HasColumnName("docente_id");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("NivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("NivelDetalleCursoId", "DocenteId")
                        .IsUnique();

                    b.ToTable("docente_nivel_detalle_curso", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.GradoSeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grado_seccion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("DescripcionGrado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion_grado");

                    b.Property<string>("DescripcionSeccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion_seccion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.HasKey("Id");

                    b.ToTable("grado_seccion", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("horario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dia_semana");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("NivelDetalleCursoId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    b.HasKey("Id");

                    b.HasIndex("NivelDetalleCursoId");

                    b.ToTable("horario", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("matricula_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("alumno_id");

                    b.Property<int?>("ApoderadoId")
                        .HasColumnType("integer")
                        .HasColumnName("apoderado_id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<bool?>("EsRepitente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_repitente");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("InstitucionProcedencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("institucion_procedencia");

                    b.Property<int>("NivelDetalleId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_id");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer")
                        .HasColumnName("periodo_id");

                    b.Property<string>("Situacion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("situacion");

                    b.Property<string>("ValorCodigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("valor_codigo");

                    b.HasKey("Id");

                    b.HasIndex("ApoderadoId");

                    b.HasIndex("NivelDetalleId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("AlumnoId", "NivelDetalleId", "PeriodoId")
                        .IsUnique();

                    b.ToTable("matricula", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("DescripcionNivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion_nivel");

                    b.Property<string>("DescripcionTurno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion_turno");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Horario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("horario");

                    b.HasKey("Id");

                    b.ToTable("nivel", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("GradoSeccionId")
                        .HasColumnType("integer")
                        .HasColumnName("grado_seccion_id");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    b.Property<int?>("TotalVacantes")
                        .HasColumnType("integer")
                        .HasColumnName("total_vacantes");

                    b.Property<int?>("VacantesOcupadas")
                        .HasColumnType("integer")
                        .HasColumnName("vacantes_ocupadas");

                    b.HasKey("Id");

                    b.HasIndex("GradoSeccionId");

                    b.HasIndex("NivelId", "GradoSeccionId")
                        .IsUnique();

                    b.ToTable("nivel_detalle", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalleCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_curso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("NivelDetalleId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_detalle_id");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("NivelDetalleId", "CursoId")
                        .IsUnique();

                    b.ToTable("nivel_detalle_curso", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("periodo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.HasKey("Id");

                    b.ToTable("periodo", (string)null);
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Codigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("direccion");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("documento_identidad");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroTelefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_telefono");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("sexo");

                    b.Property<string>("ValorCodigo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("valor_codigo");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.ToTable("persona", null, t =>
                        {
                            t.HasCheckConstraint("CK_PERSONA_DOCID_FORMAT", "(\r\n                        documento_identidad ~ '^\\d{3}-\\d{6}-\\d{3,4}[A-Z]?$'\r\n                        OR documento_identidad ~ '^TUTOR-\\d{3}-\\d{6}-\\d{3,4}[A-Z]?$'\r\n                      )");

                            t.HasCheckConstraint("CK_PERSONA_SEXO", "sexo IN ('M','F','O')");

                            t.HasCheckConstraint("CK_PERSONA_TEL_NI", "(\r\n                        numero_telefono IS NULL\r\n                        OR numero_telefono ~ '^\\+505\\d{8}$'\r\n                        OR numero_telefono ~ '^\\d{8}$'\r\n                      )");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Alumno", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne("Alumno")
                        .HasForeignKey("SIAE_LA.Domain.Entities.Alumno", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.AlumnoApoderado", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Apoderados")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.Apoderado", "Apoderado")
                        .WithMany()
                        .HasForeignKey("ApoderadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Apoderado");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Apoderado", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne("Apoderado")
                        .HasForeignKey("SIAE_LA.Domain.Entities.Apoderado", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("SIAE_LA.Domain.Entities.ApplicationUser", "PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Calificaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.Curricula", "Curricula")
                        .WithMany("Calificaciones")
                        .HasForeignKey("CurriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curricula");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curricula", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", "DocenteNivelDetalleCurso")
                        .WithMany("Curriculas")
                        .HasForeignKey("DocenteNivelDetalleCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalleCurso", null)
                        .WithMany("Curriculas")
                        .HasForeignKey("NivelDetalleCursoId");

                    b.Navigation("DocenteNivelDetalleCurso");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Docente", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Persona", "Persona")
                        .WithOne("Docente")
                        .HasForeignKey("SIAE_LA.Domain.Entities.Docente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Docente", "Docente")
                        .WithMany("Asignaciones")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalleCurso", "NivelDetalleCurso")
                        .WithMany("Docentes")
                        .HasForeignKey("NivelDetalleCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("NivelDetalleCurso");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Horario", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalleCurso", "NivelDetalleCurso")
                        .WithMany("Horarios")
                        .HasForeignKey("NivelDetalleCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelDetalleCurso");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Matriculas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.Apoderado", "Apoderado")
                        .WithMany("Matriculas")
                        .HasForeignKey("ApoderadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalle", "NivelDetalle")
                        .WithMany("Matriculas")
                        .HasForeignKey("NivelDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Apoderado");

                    b.Navigation("NivelDetalle");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalle", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.GradoSeccion", "GradoSeccion")
                        .WithMany("NivelDetalles")
                        .HasForeignKey("GradoSeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.Nivel", "Nivel")
                        .WithMany("Detalles")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradoSeccion");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalleCurso", b =>
                {
                    b.HasOne("SIAE_LA.Domain.Entities.Curso", "Curso")
                        .WithMany("Niveles")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIAE_LA.Domain.Entities.NivelDetalle", "NivelDetalle")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("NivelDetalle");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("Apoderados");

                    b.Navigation("Calificaciones");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Apoderado", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curricula", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.DocenteNivelDetalleCurso", b =>
                {
                    b.Navigation("Curriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.GradoSeccion", b =>
                {
                    b.Navigation("NivelDetalles");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Nivel", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalle", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.NivelDetalleCurso", b =>
                {
                    b.Navigation("Curriculas");

                    b.Navigation("Docentes");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SIAE_LA.Domain.Entities.Persona", b =>
                {
                    b.Navigation("Alumno");

                    b.Navigation("Apoderado");

                    b.Navigation("Docente");
                });
#pragma warning restore 612, 618
        }
    }
}
